# Generated by Django 4.2.4 on 2023-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('assetid', models.AutoField(primary_key=True, serialize=False)),
                ('assetname', models.CharField(blank=True, max_length=255, null=True)),
                ('assettype', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProcesses',
            fields=[
                ('processid', models.AutoField(primary_key=True, serialize=False)),
                ('processname', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('criticalitylevel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'businessprocesses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('contactid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'emergencycontacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('incidentid', models.AutoField(primary_key=True, serialize=False)),
                ('incidentname', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('incidentdate', models.DateField(blank=True, null=True)),
                ('responseactions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryStrategies',
            fields=[
                ('strategyid', models.AutoField(primary_key=True, serialize=False)),
                ('strategyname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recoverystrategies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('riskid', models.AutoField(primary_key=True, serialize=False)),
                ('riskname', models.CharField(blank=True, max_length=255, null=True)),
                ('likelihood', models.CharField(blank=True, max_length=255, null=True)),
                ('impacttype', models.CharField(blank=True, max_length=255, null=True)),
                ('impactscale', models.CharField(blank=True, max_length=255, null=True)),
                ('risklevel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'risks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestPlans',
            fields=[
                ('testplanid', models.AutoField(primary_key=True, serialize=False)),
                ('testplanname', models.CharField(blank=True, max_length=255, null=True)),
                ('testdate', models.DateField(blank=True, null=True)),
                ('testresult', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testplans',
                'managed': False,
            },
        ),
    ]
